#!/bin/bash
# --------------------------------
#  MacintoshPi Launcher / v.1.2.5
# --------------------------------
#  author: Jaroslaw Mazurkiewicz
#                        Jaromaz
#  e-mail: jm at iq.pl
#  www: https://jm.iq.pl
# --------------------------------
# Description:
# ------------
# Runs Mac OS (or any application)
# based on configs placed in CONF
# directory.
# --------------------------------

    BASE_DIR="/usr/share/macintoshpi"
    CONF_DIR="/etc/macintoshpi"
    LOG="/var/log/macintoshpi.log"
    SYS=$1
    SKA=$2
    SOUND=1

    # Help screen
    function hlp {
        echo "Usage: mac <COMMAND> [IMAGE_FILE]"
        echo
        echo "Runs Mac OS (or any application) based on"
        echo "configs placed in ${CONF_DIR} directory."
        echo
        echo "List of Main Commands:"
        echo
        for i in {7..9}; do echo "os${i}"; done
        [ -d "$CONF_DIR" ] && ls -1 $CONF_DIR
        echo
        exit
    }

    function log_check {
        if ! [ -f ${LOG} ]; then
            sudo touch ${LOG}
            sudo chown pi:pi ${LOG}
        fi
        echo -e "\n$(date): $SYS ----------" >> ${LOG}
    }


    function run_os {

        clear
        tput civis
        if aplay -l 2>&1 | grep "no sound"; then SOUND=0; fi
        log_check
        sleep 2
        if [ "$SOUND" -gt 0 ]; then
            sudo killall pulseaudio &>/dev/null
            sleep 1
            sudo pulseaudio -D &>/dev/null
            sleep 1
            if [ -f $BASE_DIR/sounds/os${VER}.wav ]; then
                sudo amixer -q sset Master playback 40%
                sudo aplay -q $BASE_DIR/sounds/os${VER}.wav
                sudo amixer -q sset Master playback 80%
                sleep 1
                sudo killall pulseaudio &>/dev/null
                sleep 1
                sudo pulseaudio -D &>/dev/null
                sleep 1
            fi

        fi
        [ -z "$SKA" ] || DISK="--disk $SKA"
        [ "$VER" -eq 9 ] && command="sudo "
        [ "$SOUND" -eq 1 ] && command="${command} padsp"
        [ "$VER" -eq 9 ] && command="${command} SheepShaver"
        [ "$VER" -lt 9 ] && command="${command} BasiliskII"
        ${command} --config ${MACOS_CONFIG} ${DISK} &>>${LOG}
        clear
        tput cnorm
        exit
    }

    [ -z "${SYS}" ] && hlp

    # Mac OS 7/8/9
    if [[ "$SYS" =~ ^os[[:digit:]]$ ]]; then
        VER=${SYS: -1}
        MACOS_DIR=${BASE_DIR}/macos${VER}
        MACOS_CONFIG=${MACOS_DIR}/macos${VER}.cfg

        # Autostart
        if [ "$SKA" == "macpiautostart" ]; then
            sleep 5
            clear
            SKA=""
            # Mac OS 7/8/9
            if [ "$VER" -lt 10 ]; then
                run_os
            fi
        fi
        run_os
    fi


    # Help info
    [ -d ${CONF_DIR}/${SYS} ] || hlp

    # Copy config files
    sudo cp -rf ${CONF_DIR}/${SYS}/* /
    echo "${SYS} installed - rebooting"
    clear
    sleep 1

    # Rebooting
    if [ "$SYS" == "commodore" ]; then
        sudo reboot 1
        exit
    fi

    sudo reboot
